version: '3.8'

services:
  api-service:
    build:
      context: api-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka
      - db
    env_file:
      - api-service/.env
    networks:
      - mynetwork

  data-service:
    build:
      context: data-service
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
      - kafka
      - db
    env_file:
      - data-service/.env
    networks:
      - mynetwork

  db:
    image: postgres:latest
    restart: always
    env_file:
      - postgres.env
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - mynetwork

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    env_file:
      - kafka.env
    networks:
      - mynetwork

  kafka:
    image: wurstmeister/kafka
    env_file:
      - kafka.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - mynetwork

volumes:
  data:

networks:
  mynetwork:
    driver: bridge